### ISSUE TITLE
Issue with angular-cli --aot option

### ISSUE THREAD

**Issue by mwawrusch** [jellyjs/angular2-file-drop#9]
When trying to build with --aot enabled (ng build --prod --aot) I get the following error:

```
0% compilingUnexpected value 'FileDropModule' imported by the module 'EntitiesModule'
Error: Unexpected value 'FileDropModule' imported by the module 'EntitiesModule'
    at /Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@angular/compiler/bundles/compiler.umd.js:14326:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@angular/compiler/bundles/compiler.umd.js:14311:46)
    at /Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@angular/compiler/bundles/compiler.umd.js:13284:43
    at Array.forEach (native)
    at _extractModulesAndPipesOrDirectives (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@angular/compiler/bundles/compiler.umd.js:13283:28)
    at analyzeNgModules (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@angular/compiler/bundles/compiler.umd.js:13039:16)
    at OfflineCompiler.compileModules (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@angular/compiler/bundles/compiler.umd.js:13115:20)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:71:26)
    at AotPlugin._make (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@ngtools/webpack/src/plugin.js:186:43)
    at Compiler.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/@ngtools/webpack/src/plugin.js:151:75)
    at Compiler.applyPluginsParallel (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/Compiler.js:456:7)
    at Compiler.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/Compiler.js:219:10)
    at Compiler.readRecords (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/Compiler.js:367:10)
    at Compiler.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/Compiler.js:216:9)
    at next (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/Compiler.js:213:8)
    at next (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.run (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/webpack/lib/Compiler.js:210:7)
    at /Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/angular-cli/tasks/build-webpack.js:26:29
    at Class.exports.default.Task.extend.run (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/angular-cli/tasks/build-webpack.js:25:16)
    at Class.Command.extend.run (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/mwawrusch/Documents/envy-v3/envy-shop/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by noorahmed94** [comment]
any solutions yet?

**Comment by kamilkisiela** [comment]
Try to use `0.1.0`
